<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IPContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ipcontents')->insert(
            [
                [
                    'id'=>1,
                    'name'=>'Luffy',
                    'image_file'=>'ONE_PIECE/onepiece01_luffy.png'
                ],
                [
                    'id'=>2,
                    'name'=>'Zoro',
                    'image_file'=>'ONE_PIECE/onepiece02_zoro_bandana.png'
                ],
                [
                    'id'=>3,
                    'name'=>'Nami',
                    'image_file'=>'ONE_PIECE/onepiece03_nami.png'
                ],
                [
                    'id'=>4,
                    'name'=>'Usopp',
                    'image_file'=>'ONE_PIECE/onepiece04_usopp_sogeking.png'
                ],
                [
                    'id'=>5,
                    'name'=>'Sanji',
                    'image_file'=>'ONE_PIECE/onepiece05_sanji.png'
                ],
                [
                    'id'=>6,
                    'name'=>'Chopper',
                    'image_file'=>'ONE_PIECE/onepiece06_chopper.png'
                ],
                [
                    'id'=>7,
                    'name'=>'Robin',
                    'image_file'=>'ONE_PIECE/onepiece07_robin.png'
                ],
                [
                    'id'=>8,
                    'name'=>'Franky',
                    'image_file'=>'ONE_PIECE/onepiece08_franky.png'
                ],
                [
                    'id'=>9,
                    'name'=>'Brook',
                    'image_file'=>'ONE_PIECE/onepiece09_brook.png'
                ],
                [
                    'id'=>10,
                    'name'=>'Jinbe',
                    'image_file'=>'ONE_PIECE/onepiece10_jinbe.png'
                ],
                [
                    'id'=>11,
                    'name'=>'Arlong',
                    'image_file'=>'ONE_PIECE/onepiece11_arlong.png'
                ],
                [
                    'id'=>12,
                    'name'=>'Buggy',
                    'image_file'=>'ONE_PIECE/onepiece12_buggy.png'
                ],
                [
                    'id'=>13,
                    'name'=>'Crocodile',
                    'image_file'=>'ONE_PIECE/onepiece13_crocodile.png'
                ],
                [
                    'id'=>14,
                    'name'=>'Enel',
                    'image_file'=>'ONE_PIECE/onepiece14_enel.png'
                ],
                [
                    'id'=>15,
                    'name'=>'Lucci',
                    'image_file'=>'ONE_PIECE/onepiece15_lucci.png'
                ],
                [
                    'id'=>16,
                    'name'=>'Moria',
                    'image_file'=>'ONE_PIECE/onepiece16_moria.png'
                ],
                [
                    'id'=>17,
                    'name'=>'Doflamingo',
                    'image_file'=>'ONE_PIECE/onepiece17_doflamingo.png'
                ],
                [
                    'id'=>18,
                    'name'=>'Linlin_Kaido',
                    'image_file'=>'ONE_PIECE/onepiece18_linlin_kaido.png'
                ],
                [
                    'id'=>19,
                    'name'=>'Kurohige_tech2',
                    'image_file'=>'ONE_PIECE/onepiece19_kurohige_teach2.png'
                ],
                [
                    'id'=>20,
                    'name'=>'Santaisyou',
                    'image_file'=>'ONE_PIECE/onepiece20_santaisyou.png'
                ],
            ]
        );
    }
}
